export interface Product {
  id: string;
  name: string;
  price: number;
  category: 'bolso' | 'accesorio';
  subcategory?: string;
  description: string;
  image: string;
  images?: string[];
  colors: string[];
  materials: string[];
  dimensions: string;
  featured?: boolean;
  new?: boolean;
  rating?: number;
}

export const products: Product[] = [
  // BOLSOS (14 productos)
  {
    id: 'bolso-chio',
    name: 'Bolso Chio',
    price: 180,
    category: 'bolso',
    description: 'Estructura aafirme, asas tejidas dobles y detalle en cadena dorada. Sofisticada y funcional, es perfecta para acompañarte en cualquier ocasión con un toque único y artesanal.',
    image: '/images/bolso-chio-1.png',
    images: [
      '/images/bolso-chio-22.png',
    ],
    colors: ['Terracota', 'Negro', 'Topo', 'Rosa', 'Blanco'],
    materials: ['Algodón Highlight', 'Cordones de algodón'],
    dimensions: '35cm x 28cm x 10cm',
    featured: true, 
    rating: 4.9,
  },
  {
    id: 'bolso-victoria',
    name: 'Bolso Victoria',
    price: 180,
    category: 'bolso',
    description: 'Diseño exclusivo con asas metálicas inoxidables doradas y cadena decorativa removible. Interior forrado, ideal para complementar tu estilo.',
   image: '/images/bolso-victoria-1.png',
    images: [
      '/images/bolso-victoria-2.png',
    ],
    colors: ['Azul', 'Negro', 'Beige', 'Marrón', 'Blanco'],
    materials: ['Trapillo', 'Cordones sintéticos'],
    dimensions: '27cm x 25cm x 10cm',
    featured: true,
    rating: 4.7,
  },
  {
    id: 'bolso-alessandra',
    name: 'Bolso Alessandra',
    price: 200,
    category: 'bolso',
    description: 'Cierre metálico, asas firmes y herrajes bañados en oro que aportan un toque sofisticado. ',
    image: '/images/bolso-alessandra-1.png',
    images: [
      '/images/bolso-alessandra-2.png',
      '/images/bolso-alessandra-3.png',
    ],
    colors: ['Rojo', 'Negro', 'Beige', 'Azul', 'Blanco'],
    materials: ['Algodón Highlight', 'Cola de rata'],
    dimensions: '25cm x 15cm x 10cm',
    featured: true,
    rating: 4.8,
  },
  {
    id: 'bolso-isabel',
    name: 'Bolso Isabel',
    price: 165,
    category: 'bolso',
    description: 'Diseño versátil para uso diario, cómodo, ligero y único en cada pieza. Asa ancha para mayor comodidad. Cierre seguro y forro interno.',
    image: '/images/bolso-isabel-1.png',
    images: [
      '/images/bolso-isabel-2.png',
      '/images/bolso-isabel-3.png',
    ],
    colors: ['Marrón', 'Negro', 'Azul', 'Terracota', 'Blanco'],
    materials: ['Trapillo', 'Cordones de algodón'],
    dimensions: '20cm x 15cm x 10cm', 
    rating: 4.5,
  },
  {
    id: 'bolso-liseth',
    name: 'Bolso Liseth',
    price: 200,
    category: 'bolso',
    description: 'Diseño estructurado y resistente. Cuenta con amplio espacio interior y compartimentos funcionales para organizar esenciales de trabajo y uso diario con estilo.',
    image: '/images/bolso-liseth-1.png',
    images: [
      '/images/bolso-liseth-2.png',
    ],
    colors: ['Marrón', 'Negro', 'Azul', 'Terracota', 'Blanco'],
    materials: ['Algodón Highlight'],
    dimensions: '30cm x 25cm x 15cm',
    rating: 4.7,
  },
  {
    id: 'bolso-marie',
    name: 'Bolso Maríe',
    price: 175,
    category: 'bolso',
    description: 'Bolso compacto de diseño femenino y sofisticado. Su asa firme, adornada con cadena dorada y borla decorativa, eleva cualquier look con elegancia.',
    image: 'https://images.unsplash.com/photo-1605735940798-5201db29e5e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwcHVyc2UlMjBjb2xvcmZ1bHxlbnwxfHx8fDE3NjQ4OTkzNTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rosa', 'Negro', 'Rojo', 'Azul', 'Blanco'],
    materials: ['Cordones de algodón', 'Trapillo'],
    dimensions: '25cm x 20cm x 10cm',
    rating: 4.3,
  },
  {
    id: 'bolso-elena',
    name: 'Bolso Elena',
    price: 165,
    category: 'bolso',
    description: 'Bolso de elegancia clásica y silueta estructurada. Sus detalles metálicos y su distinguido broche frontal lo convierten en el complemento ideal para un look sofisticado.',
    image: '/images/bolso-elena-1.png',
    images: [
      '/images/bolso-elena-2.png',
    ],
    colors: ['Marrón', 'Negro', 'Azul', 'Terracota', 'Blanco'],
    materials: ['Cola de rata', 'Algodón Highlight'],
    dimensions: '20cm x 15cm x 10cm',
    rating: 4.6,
  },
  {
    id: 'bolso-elisa',
    name: 'Bolso Elisa',
    price: 160,
    category: 'bolso',
    description: 'Bolso de líneas fluidas y silueta moderna. Su asa de hombro integrada y su estructura ligera lo convierten en un básico sofisticado y versátil para tu look diario.',
    image: '/images/bolso-elisa-1.png',
    images: [
      '/images/bolso-elisa-2.png',
    ],
    colors: ['Marrón', 'Negro', 'Beige', 'Azul', 'Blanco'],
    materials: ['Cordones sintéticos', 'Algodón Highlight'],
    dimensions: '36cm x 25cm x 15cm',
    rating: 4.8,
  },
  {
    id: 'bolso-bella',
    name: 'Bolso Bellá',
    price: 190,
    category: 'bolso',
    description: 'Bolso de silueta estructurada tipo maletín. Su audaz diseño de franjas en degradé y su elegante broche metálico lo convierten en un accesorio único y lleno de personalidad.',
    image: 'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Azul', 'Negro', 'Rosa', 'Terracota', 'Blanco'],
    materials: ['Trapillo', 'Cordones sintéticos'],
    dimensions: '27cm x 25cm x 10cm',
    rating: 4.9,
  },
  {
    id: 'bolso-rosie',
    name: 'Bolso Rosie',
    price: 200,
    category: 'bolso',
    description: 'Bolso de diseño icónico, inspirado en la elegancia atemporal. Destaca por sus herrajes dorados, candado y el delicado pañuelo en el asa, creando un accesorio que irradia sofisticación.',
    image: '/images/bolso-rosie-1.png',
    images: [
      '/images/bolso-rosie-2.png',
    ],
    colors: ['Rosa', 'Negro', 'Azul', 'Terracota', 'Blanco'],
    materials: ['Cola de rata', 'Algodón Highlight'],
    dimensions: '40cm x 30cm x 15cm',
    rating: 4.9,
  },
  {
    id: 'bolso-leonor',
    name: 'Bolso Leonor',
    price: 170,
    category: 'bolso',
    description: 'Bolso de diseño funcional y silueta estructurada. Destaca por sus prácticos compartimentos laterales y un elegante broche de giro, creando un accesorio espacioso y sofisticado.',
    image: 'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rojo', 'Negro', 'Azul', 'Topo', 'Blanco'],
    materials: ['Cordones de algodón', 'Trapillo'],
    dimensions: '40cm x 30cm x 15cm',
    rating: 4.4,
  },
  {
    id: 'bolso-emma',
    name: 'Bolso Emma',
    price: 150,
    category: 'bolso',
    description: 'Bolso versátil de estructura compacta, con asa de mano y correa larga removible. El elegante broche de giro y la llamativa borla lateral le aportan un toque bohemio y sofisticado.',
    image: 'https://images.unsplash.com/photo-1619468918235-8eb7dd64a7b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMGNyYWZ0cyUyMGJvaGVtaWFufGVufDF8fHx8MTc2NDg5OTM2MXww&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Marrón', 'Negro', 'Azul', 'Terracota', 'Blanco'],
    materials: ['Cordones de algodón', 'Algodón Highlight'],
    dimensions: '20cm x 15cm x 10cm',
    rating: 4.7,
  },
  {
    id: 'bolso-gabriela',
    name: 'Bolso Gabriela',
    price: 160,
    category: 'bolso',
    description: 'Bolso de diseño tote, espacioso y contemporáneo. Sus asas de mano integradas y su correa larga removible ofrecen máxima versatilidad, convirtiéndolo en el aliado perfecto para tu rutina diaria.',
    image: '/images/bolso-gabriela-1.png',
    images: [
      '/images/bolso-gabriela-2.png',
    ],
    colors: ['Rojo', 'Negro', 'Azul', 'Topo', 'Blanco'],
    materials: ['Trapillo', 'Cordones sintéticos'],
    dimensions: '40cm x 30cm x 15cm',
    rating: 4.9,
  },
  {
    id: 'bolso-elida',
    name: 'Bolso Elida',
    price: 175,
    category: 'bolso',
    description: 'Bolso de diseño audaz y estructura definida. Destaca por su singular asa trenzada que se entrelaza con argollas metálicas y una cadena decorativa, creando un accesorio moderno y lleno de carácter.',
    image: '/images/bolso-elida-1.png',
    images: [
      '/images/bolso-elida-2.png',
    ],
    colors: ['Rojo', 'Negro', 'Azul', 'Topo', 'Blanco'],
    materials: ['Cola de rata', 'Algodón Highlight'],
    dimensions: '30cm x 20cm x 15cm',
    rating: 4.7,
  },

  // ACCESORIOS (8 productos)
  {
    id: 'monedero-eliza',
    name: 'Monedero Eliza',
    price: 35,
    category: 'accesorio',
    subcategory: 'monedero',
    description: 'Su diseño compacto, realzado por una trenza lateral y un seguro broche metálico, combina practicidad y estilo.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rosa', 'Celeste', 'Gris'],
    materials: ['Algodón Highlight'],
    dimensions: '10cm x 10cm x 5cm',
    rating: 4.3,
  },
  {
    id: 'monedero-cristy',
    name: 'Monedero Cristy',
    price: 25,
    category: 'accesorio',
    subcategory: 'monedero',
    description: 'Un clásico reinventado. Este monedero destaca por su tejido de textura abullonada y su icónico cierre de boquilla metálica, evocando un encanto vintage y femenino.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rosa', 'Terracota'],
    materials: ['Cola de rata'],
    dimensions: '7cm x 7cm x 5cm',
    rating: 4.6,
  },
  {
    id: 'llavero-esencia',
    name: 'Llavero Esencia',
    price: 15,
    category: 'accesorio',
    subcategory: 'llavero',
    description: 'Un detalle único que te acompaña siempre. Este llavero, tejido a mano con un detallado diseño de nudos, se personaliza con tu nombre o palabra favorita en cuentas de madera.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Marfil', 'Verde oliva', 'Oliva oscuro'],
    materials: ['Algodón Highlight', 'Cola de rata'],
    dimensions: '10cm x 3cm x 3cm',
    rating: 4.9,
  },
  {
    id: 'porta-airpods',
    name: 'Porta AirPods',
    price: 30,
    category: 'accesorio',
    subcategory: 'porta-pods',
    description: 'Diseñada para protegerlos con estilo, esta funda compacta cuenta con un seguro cierre de botón y una práctica correa para que los lleves siempre contigo.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rosa', 'Blanco', 'Marrón', 'Terracota', 'Gris'],
    materials: ['Algodón Highlight'],
    dimensions: '6cm x 5cm x 3cm',
    rating: 4.3,
  },
  {
    id: 'cosmetiquera-molie',
    name: 'Cosmetiquera Molie',
    price: 45,
    category: 'accesorio',
    subcategory: 'cosmetiquera',
    description: 'Mantén tus esenciales de belleza organizados en esta cosmetiquera de tejido suave. Su diseño minimalista y cierre seguro combinan a la perfección la simpleza, la elegancia y la practicidad.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Beige'],
    materials: ['Cordones de algodón', 'Trapillo'],
    dimensions: '10cm x 5cm x 7cm',
    rating: 4.5,
  },
  {
    id: 'cosmetiquera-lisie',
    name: 'Cosmetiquera Lisie',
    price: 40,
    category: 'accesorio',
    subcategory: 'cosmetiquera',
    description: 'Su diseño plano y elegante la convierte en el accesorio perfecto, funcionando tanto como cosmetiquera como un moderno bolso de mano. Equipada con un cierre seguro y una práctica correa de muñeca, es ideal para llevar tus esenciales con estilo y comodidad.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Crema'],
    materials: ['Algodón Highlight'],
    dimensions: '10cm x 7cm x 5cm',
    rating: 4.9,
  },
  {
    id: 'tarjetero-ines',
    name: 'Tarjetero Inés',
    price: 18,
    category: 'accesorio',
    subcategory: 'tarjetero',
    description: 'Su diseño compacto y minimalista, asegurado con un broche a presión, te permite organizar tus tarjetas con elegancia y sin añadir volumen. ',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Rosa', 'Beige', 'Rojo', 'Azul'],
    materials: ['Cola de rata', 'Algodón Highlight'],
    dimensions: '7cm x 5cm x 2cm',
    rating: 4.6,
  },
  {
    id: 'porta-libretas',
    name: 'Porta Libretas',
    price: 25,
    category: 'accesorio',
    subcategory: 'porta-libretas',
    description: 'Su diseño funcional se asegura con un encantador botón de madera, manteniendo todo en su lugar. Un accesorio esencial para transportar y proteger tus notas e inspiración con un toque especial.',
    image: 'https://images.unsplash.com/photo-1753370474751-c15e55efb1a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
     images: [
      'https://images.unsplash.com/photo-1759544632264-a31a9ff1e60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9jaGV0JTIwYmFnJTIwaGFuZG1hZGV8ZW58MXx8fHwxNzY0ODU5MjYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1615485737442-7d6ab9f64db9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kbWFkZSUyMHRleHRpbGUlMjBiYWd8ZW58MXx8fHwxNzY0ODk5MzU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    colors: ['Verde', 'Blanco'],
    materials: ['Cordones de algodón', 'Trapillo'],
    dimensions: '25cm x 20cm x 5cm',
    rating: 4.7,
  },
];

export const getBolsos = () => products.filter(p => p.category === 'bolso');
export const getAccesorios = () => products.filter(p => p.category === 'accesorio');
export const getFeaturedProducts = () => products.filter(p => p.featured);
export const getProductById = (id: string) => products.find(p => p.id === id);
